name:                DeliveryService
version:             0.1.0.0
github:              "YanDoroshenko/DeliveryService"
license:             GPLv3
author:              "Yan Doroshenko"
maintainer:          "yandoroshenko@protonmail.com"
copyright:           "2021 Yan Doroshenko"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/DeliveryService#readme>

dependencies:
- base >= 4.7 && < 5
- cql-io >= 1.1.1
- cql >= 4.0
- text >= 1.2.4.1
- tinylog >= 0.15.0
- scotty >= 0.12
- http-types >= 0.12
- Decimal >= 0.5.2
- aeson >= 1.5.6

library:
  source-dirs: src

executables:
  DeliveryService-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - DeliveryService

tests:
  DeliveryService-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - DeliveryService
